package product

// PlatformMatrix is the canonical, ordered list of every (GOOS, GOARCH) pair
// graphics.gd supports as either a host (where gdnext runs) or a build
// target (where the engine + a graphics.gd app can run).
var PlatformMatrix = []Platform{
	// --- Linux ----------------------------------------------------------
	{
		Title:     "Linux x86_64",
		GOOS:      "linux",
		GOARCH:    "amd64",
		Aliases:   []string{"ubuntu", "arch", "debian", "nix", "ublue/bazzite"},
		Kind:      Host | Target,
		Status:    Supported | Stable,
		Renderers: []string{"vulkan", "opengl3", "gl_compatibility"},
	},
	{
		Title:     "Linux ARM64",
		GOOS:      "linux",
		GOARCH:    "arm64",
		Kind:      Target,
		Status:    Supported,
		Renderers: []string{"vulkan", "opengl3", "gl_compatibility"},
		Notes:     "cross-compiled from any host via zig",
	},
	// --- Windows --------------------------------------------------------
	{
		Title:     "Windows x86_64",
		GOOS:      "windows",
		GOARCH:    "amd64",
		Aliases:   []string{"win"},
		Kind:      Host | Target,
		Status:    Supported | Stable,
		Renderers: []string{"vulkan", "opengl3", "gl_compatibility"},
	},
	{
		Title:     "Windows ARM64",
		GOOS:      "windows",
		GOARCH:    "arm64",
		Kind:      Target,
		Status:    Experimental,
		Renderers: []string{"vulkan", "opengl3", "gl_compatibility"},
	},
	// --- macOS ----------------------------------------------------------
	{
		Title:     "macOS x86_64",
		GOOS:      "darwin",
		GOARCH:    "amd64",
		Aliases:   []string{"macos"},
		Kind:      Host | Target,
		Status:    Supported | Stable,
		Renderers: []string{"metal", "opengl3", "gl_compatibility"},
		Notes:     "exports as a universal .app alongside arm64",
	},
	{
		Title:     "macOS Apple Silicon",
		GOOS:      "darwin",
		GOARCH:    "arm64",
		Kind:      Host | Target,
		Status:    Supported | Stable,
		Renderers: []string{"metal", "opengl3", "gl_compatibility"},
	},
	// --- iOS ------------------------------------------------------------
	{
		Title:     "iOS ARM64",
		GOOS:      "ios",
		GOARCH:    "arm64",
		Aliases:   []string{"iphone"},
		Kind:      Target,
		Status:    Supported,
		Renderers: []string{"metal", "gl_compatibility"},
		Notes:     "requires llvm; signing needs a macOS host + Apple cert",
	},
	// --- Android --------------------------------------------------------
	{
		Title:     "Android ARM64",
		GOOS:      "android",
		GOARCH:    "arm64",
		Kind:      Target,
		Status:    Supported | Stable,
		Renderers: []string{"vulkan", "gl_compatibility"},
	},
	{
		Title:     "Android x86_64",
		GOOS:      "android",
		GOARCH:    "amd64",
		Kind:      Target,
		Status:    Supported | Quirky,
		Renderers: []string{"vulkan", "gl_compatibility"},
		Notes:     "primarily emulator or desktop android targeted (ex: waydroid)",
	},
	// --- Meta Quest (Android variant with OpenXR loader) ---------------
	{
		Title:     "Meta Quest",
		GOOS:      "metaquest",
		GOARCH:    "arm64",
		Aliases:   []string{"quest", "meta"},
		Kind:      Target,
		Status:    Supported,
		Renderers: []string{"vulkan"},
		Notes:     "Android profile with GodotVR + OpenXR injected into the apk",
	},
	// --- Web (WebAssembly + WebGL) -------------------------------------
	{
		Title:     "Web (WebAssembly)",
		GOOS:      "js",
		GOARCH:    "wasm",
		Aliases:   []string{"web", "browser", "wasm"},
		Kind:      Target,
		Status:    Supported,
		Renderers: []string{"gl_compatibility"},
		Notes:     "COEP/COOP headers required when serving",
	},
	// --- musl (static-linked Linux) ------------------------------------
	{
		Title:     "Linux musl x86_64",
		GOOS:      "musl",
		GOARCH:    "amd64",
		Kind:      Target,
		Status:    Experimental,
		Renderers: []string{"vulkan", "opengl3", "gl_compatibility"},
		Notes:     "fully-static linux binary; runs on any libc",
	},
	{
		Title:     "Linux musl ARM64",
		GOOS:      "musl",
		GOARCH:    "arm64",
		Kind:      Target,
		Status:    Experimental,
		Renderers: []string{"vulkan", "opengl3", "gl_compatibility"},
	},
}

// ToolchainMatrix is the canonical, ordered list of every external program
// graphics.gd's build pipeline can drive. Order matters: it's the order
// `gdnext toolchain {list,doctor}` use when rendering their tables and the
// order `gdnext toolchain install` (no args) walks. Keep base-required
// tools (godot, go, zig) first.
var ToolchainMatrix = []Toolchain{
	{
		Slug:          "godot",
		Name:          "godot",
		Version:       "4.6.2",
		VersionFlags:  []string{"--version"},
		VersionPrefix: "4.6.",
		RequiredFor:   "graphics",
		Required:      AllPlatforms,
		DownloadHint:  "https://godotengine.org/download",
		DownloadURL:   "https://github.com/godotengine/godot/releases/download/$(VERSION)-stable/Godot_v$(VERSION)-stable_$(OS).zip",
		DownloadOS:    map[string]string{"windows": "win64.exe", "linux": "linux.$(ARCH)", "darwin": "macos.universal"},
		DownloadARCH:  map[string]string{"amd64": "x86_64", "arm64": "arm64"},
		Unzip:         "Godot_v$(VERSION)-stable_$(OS)",
		IsApp:         true,
		ConvertArguments: map[string]string{
			"-v":       "--verbose",
			"-x":       "",
			"-gcflags": "",
		},
	},
	{
		Slug:          "go",
		Name:          "go",
		Version:       "1.26.0",
		VersionFlags:  []string{"version"},
		VersionPrefix: "go version go1.26.",
		RequiredFor:   "compiling",
		Required:      AllPlatforms,
		DownloadHint:  "https://go.dev/dl/",
		ConvertArguments: map[string]string{
			"--verbose": "-v",
		},
	},
	{
		Slug:         "zig",
		Name:         "zig",
		Version:      "0.15.2",
		VersionFlags: []string{"version"},
		RequiredFor:  "cross-compiling",
		Required:     AllPlatforms,
		DownloadHint: "https://ziglang.org/download/",
		DownloadURL:  "https://ziglang.org/download/$(VERSION)/zig-$(ARCH)-$(OS)-$(VERSION)$(EXT)",
		DownloadOS:   map[string]string{"windows": "windows", "darwin": "macos", "linux": "linux"},
		DownloadARCH: map[string]string{"amd64": "x86_64", "arm64": "aarch64"},
		DownloadEXT:  map[string]string{"windows": ".zip", "darwin": ".tar.xz", "linux": ".tar.xz"},
	},
	{
		Slug:          "llvm",
		Name:          "llvm",
		Version:       "21.1.8",
		VersionFlags:  []string{"clang", "--version"},
		VersionPrefix: "clang version 21.",
		RequiredFor:   "linking iOS builds",
		Required:      Platforms{GOOS: []string{"ios"}},
		DownloadURL:   "https://release.graphics.gd/llvm.$(GOOS).$(GOARCH)$(EXT)",
		DownloadEXT:   map[string]string{"linux": "", "windows": ".exe", "darwin": ""},
	},
	{
		Slug:            "adb",
		Name:            "adb",
		Version:         "1.0.41",
		VersionFlags:    []string{"--version"},
		VersionPrefix:   "Android Debug Bridge version 1.0.41",
		RequiredFor:     "launching the project on a connected android device",
		Required:        Platforms{GOOS: []string{"android", "metaquest"}},
		DownloadURL:     "https://release.graphics.gd/adb.$(GOOS).$(GOARCH)$(EXT)",
		DownloadEXT:     map[string]string{"linux": "", "windows": ".zip", "darwin": ""},
		DarwinUniversal: true,
	},
	{
		Slug:         "apksigner",
		Name:         "apksigner",
		Version:      "0.9",
		VersionFlags: []string{"--version"},
		RequiredFor:  "building the .apk",
		Required:     Platforms{GOOS: []string{"android", "metaquest"}},
		DownloadURL:  "https://release.graphics.gd/apksigner.$(GOOS).$(GOARCH)$(EXT)",
		DownloadEXT:  map[string]string{"linux": "", "windows": ".exe", "darwin": ""},
	},
	{
		Slug:            "aapt2",
		Name:            "aapt2",
		Version:         "2.19-android-13.0.0_r6",
		VersionFlags:    []string{"version"},
		VersionPrefix:   "Android Asset Packaging Tool (aapt) 2.",
		RequiredFor:     "converting the exported .apk into an .aab",
		Required:        Platforms{GOOS: []string{"android", "metaquest"}},
		DownloadURL:     "https://release.graphics.gd/aapt2.$(GOOS).$(GOARCH)$(EXT)",
		DownloadEXT:     map[string]string{"linux": "", "windows": ".exe", "darwin": ""},
		DarwinUniversal: true,
	},
	{
		Slug:          "apktool",
		Name:          "apktool",
		Version:       "2.12.1",
		VersionFlags:  []string{"v"},
		VersionPrefix: "2.12.1-",
		RequiredFor:   "converting the exported .apk into an .aab",
		Required:      Platforms{GOOS: []string{"android", "metaquest"}},
		DownloadURL:   "https://release.graphics.gd/apktool.$(GOOS).$(GOARCH)$(EXT)",
		DownloadEXT:   map[string]string{"linux": "", "windows": ".exe", "darwin": ""},
	},
	{
		Slug:         "bundletool",
		Name:         "bundletool",
		Version:      "1.18.3",
		VersionFlags: []string{"version"},
		RequiredFor:  "converting the exported .apk into an .aab",
		Required:     Platforms{GOOS: []string{"android", "metaquest"}},
		DownloadURL:  "https://release.graphics.gd/bundletool.$(GOOS).$(GOARCH)$(EXT)",
		DownloadEXT:  map[string]string{"linux": "", "windows": ".exe", "darwin": ""},
	},
	{
		Slug:        "android.jar",
		Name:        "android.jar",
		RequiredFor: "converting the exported .apk into an .aab",
		Required:    Platforms{GOOS: []string{"android", "metaquest"}},
		DownloadURL: "https://release.graphics.gd/android.jar",
		IsLibrary:   true,
	},
	{
		Slug:          "upx",
		Name:          "upx",
		Version:       "5.0.2",
		VersionFlags:  []string{"--version"},
		VersionPrefix: "upx 5.0.2",
		RequiredFor:   "minifying builds",
		// Optional: opt-in minifier, not required by any gdnext build target.
		DownloadHint: "https://github.com/upx/upx/releases/latest",
		Downloads: map[string]map[string]string{
			"windows": {
				"amd64": "https://github.com/upx/upx/releases/download/v$(VERSION)/upx-$(VERSION)-win64.zip",
			},
		},
		DownloadURL:  "https://github.com/upx/upx/releases/download/v$(VERSION)/upx-$(VERSION)-$(ARCH)_$(OS).zip",
		DownloadOS:   map[string]string{"linux": "linux"},
		DownloadARCH: map[string]string{"amd64": "amd64", "arm64": "arm64"},
	},
	{
		Slug:          "vpk",
		Name:          "vpk",
		Version:       "0.0.1298",
		VersionFlags:  []string{"--help"},
		VersionPrefix: "Description:\n  Velopack CLI 0.0.1298,",
		RequiredFor:   "self-updating-bundles",
		// Optional: not required by any gdnext build target. Used only when
		// the user explicitly wants self-updating windows bundles.
	},
	{
		Slug:        "libgodot",
		Name:        "libgodot.$(GOOS).$(GOARCH).$(EXT)",
		RequiredFor: "musl systems & single binaries",
		Required:    Platforms{GOOS: []string{"musl"}},
		DownloadURL: "https://release.graphics.gd/libgodot.$(GOOS).$(GOARCH).$(EXT)",
		DownloadEXT: map[string]string{"musl": "a", "linux": "a", "windows": "lib", "darwin": "a"},
		IsLibrary:   true,
	},
	{
		Slug:        "libgodot-editor",
		Name:        "libgodot.$(GOOS).editor.$(GOARCH).$(EXT)",
		RequiredFor: "launching the editor on musl systems",
		Required:    Platforms{GOOS: []string{"musl"}},
		DownloadURL: "https://release.graphics.gd/libgodot.$(GOOS).editor.$(GOARCH).$(EXT)",
		DownloadEXT: map[string]string{"musl": "a", "linux": "a", "windows": "lib", "darwin": "a"},
		IsLibrary:   true,
	},
	{
		Slug:        "ldd",
		Name:        "ldd",
		RequiredFor: "musl detection",
		Available:   Platforms{GOOS: []string{"linux"}},
	},
}
